org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# The Minecraft/NeoForge version this mod targets.
minecraft_version=26.1.2
neo_version=26.1.2.100
neo_version_range=[26.1.2,26.2)
loader_version_range=[1,)

# Java toolchain
java_version=25

# The mapping channel to use for mappings.
# NeoForge for 26.1+ removes obfuscation entirely, so no mapping channel/version is needed.

# The unique mod identifier for the mod. Must be lowercase in English locale.
mod_id=rogueplanets
# The human-readable display name for the mod.
mod_name=Rogue Planets
# The license of the mod.
mod_license=All Rights Reserved
# The mod version.
mod_version=1.0
# The group ID for the mod.
mod_group_id=yaboichips
# The authors of the mod.
mod_authors=yaboichips
# The description of the mod.
mod_description=roguelike

infiniverse_version=26.1.0.1
geckolib_version=5.5.2
